
%% LilyPond file generated by Denemo version 2.2.0

%%http://www.gnu.org/software/denemo/

\version "2.18.0"

CompactChordSymbols = {}
#(define DenemoTransposeStep 0)
#(define DenemoTransposeAccidental 0)
DenemoGlobalTranspose = #(define-music-function (parser location arg)(ly:music?) #{\transpose c c#arg #})
titledPiece = {}
AutoBarline = {}
AutoEndMovementBarline = \bar "|."

% The music follows

MvmntIVoiceI = {
         c'4 d' e' f'\AutoBarline
         g' ais' b' c''\AutoBarline
         ees'' e'' dis'' a'\AutoBarline
         a' a' a'' g''\AutoBarline
%5
         f' d' c' eis''\AutoBarline
         b' ces'' f'' f'\AutoBarline
         g' g' a' e'\AutoBarline
         f'' e'' d'' c''\AutoBarline
         d'' e'' f'' g''\AutoBarline
%10
         a'' b'' b c'\AutoBarline
         d' e' f' e'\AutoBarline
         dis' c' a' bis'\AutoBarline
         b' e'' d' g'\AutoBarline
         des' f' e' c'\AutoBarline
%15
         c'' c''' bis'' a''\AutoBarline
         e' f' a'' b''\AutoBarline
         c''' c''' cis''' b''\AutoBarline
         bes'' f' fis' ces'\AutoBarline
         cis'' f'' fes'' fes''\AutoBarline
%20
         f'' e'' b' b'\AutoBarline
         b' bes' gis' ais'\AutoBarline
         bis' gis'' ees' ees'\AutoBarline
         d'' c'' dis'' a'\AutoBarline
         cis' e'' f'' f''\AutoBarline
%25
         ces'' a' g' gis' \AutoEndMovementBarline
}





%Default Score Layout
\header{DenemoLayoutName = "Default Score Layout"
        instrumentation = \markup { \with-url #'"scheme:(d-BookInstrumentation)" "Full Score"}
        }

\header {
tagline = \markup {"" on \simple #(strftime "%x" (localtime (current-time)))}

        }
#(set-default-paper-size "a4")
#(set-global-staff-size 18)
\paper {

       }

\score { %Start of Movement
          <<

%Start of Staff
\new Staff = "Part 1"  << 
 \new Voice = "MvmntIVoiceI"  { 
  \clef treble    \key c \major    \time 4/4   \MvmntIVoiceI
                        } %End of voice

                        >> %End of Staff

          >>

       } %End of Movement



